language: python
os:
    - linux
python:
    - "2.7"

# Installs rcm and ansible
before_install:
    - wget https://thoughtbot.github.io/rcm/debs/rcm_1.2.3-1_all.deb
    - sudo dpkg -i rcm_1.2.3-1_all.deb
    - sudo pip install ansible

# Install inventory file and the dotfiles-local repository
install:
    - mkdir /etc/ansible
    - echo "[dev]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
    - ln -s $TRAVIS_BUILD_DIR $HOME/dotfiles-local

# Installs dotfiles using rcup
script: >
    ansible-playbook
    --connection=local --verbose
    $TRAVIS_BUILD_DIR/playbook.yml
