services:
  base:
    build: .
  codespace:
    build:
      context: .
      dockerfile: docker/codespace/Dockerfile
    entrypoint: bash
  shell:
    extends: base
    volumes:
      - ./:/root/.langri-sha-dotfiles
