#!/bin/sh
set -e

TAGDIR=$(dirname $(dirname $0))
BASEDIR=$(dirname $TAGDIR)
FONTDIR=$TAGDIR/local/share/fonts
EXTDIR=$TAGDIR/local/share/gnome-shell/extensions

. $BASEDIR/hooks/share.sh

test -e $FONTDIR || mkdir -p $FONTDIR
test -e $EXTDIR || mkdir -p $EXTDIR

# Download and install ProFont
url=http://tobiasjung.name/downloadfile.php
file=profont-x11.7z
output=$DOTFILES_TMP/$file

if [ ! -e $output ]; then
    curl \
        --location --get --data file=$file \
        --output $output \
        $url
fi

7z e -y -ir!*.pcf $output -o$FONTDIR

# Download and install Inconsolata
url=http://www.levien.com/type/myfonts/Inconsolata.otf
output=$FONTDIR/$(basename $url)

test -e $output || curl --output $output $url

# Download and install gnome-shell-impatience extension
url=http://gfxmonk.net/dist/0install/impl/gnome-shell-impatience/gnome-shell-impatience-0.4.2.tar.gz
file=$(basename $url)
extdir=$EXTDIR/impatience@gfxmonk.net

if [ ! -e $DOTFILES_TMP/$file ]; then
    curl --output $DOTFILES_TMP/$file $url
fi

if [ ! -e $extdir ]; then
    mkdir $extdir
fi

tar -xf $DOTFILES_TMP/$file \
    --directory=$extdir \
    --strip=1 \
    impatience/

# Download and install dash-to-dock extension
url=https://github.com/micheleg/dash-to-dock/archive/extensions.gnome.org-v35.tar.gz
output=$DOTFILES_TMP/dash-to-dock-v35.tar.gz
tmp=$DOTFILES_TMP/dash-to-dock

if [ ! -e $output ]; then
    curl --location --output $output $url
fi

if [ ! -e $tmp ]; then
    mkdir $tmp
fi

tar -xf $output --directory=$tmp --strip=1
cd $tmp
make INSTALLBASE=$EXTDIR install

# Download and install dash-hotkeys
url=https://github.com/franziskuskiefer/app-keys-gnome-shell-extension/archive/fc3a2248c7.tar.gz
file=app-keys-gnome-shell-extension-master-fc3a2248c7.tar.gz
extdir=$EXTDIR/unitylike-hotkey@webgyerek.net

if [ ! -e $DOTFILES_TMP/$file ]; then
    curl --location --output $DOTFILES_TMP/$file $url
fi

if [ ! -e $extdir ]; then
    mkdir $extdir
fi

tar -xf $DOTFILES_TMP/$file --directory=$extdir --strip=1
