name: Workspace

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  codespace:
    name: Codespace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Codespace environment
        run: |
          docker compose build codespace
